### PR TITLE
OLED burn-in prevention

### LINKED ISSUE #4: Burn-in on OLED screens
Some phones (such as Nokia N9) have OLED screens, and those can be damaged by displaying same image on same place for too long... (burn-in). It would be nice to move stuff on the screen, randomly, to avoid that...

### PR DESCRIPTION
**Pull request by ata2001**
Fixes #4

### CODE REVIEW

**Comment by ollieparanoid** [comment]
@ata2001: thanks a lot for making the PR!

@pavelmachek, @IanS: General question: this PR added `ifdef OLED_SCREEN` to be consistent with `ifdef USE_LIBBATTERY` which you guys introduced. We will probably package only one version of this program with postmarketOS, so does it make sense to have multiple variants to compile it based on `ifdef`s? I could imagine that this might make the code a bit less readable. (If this should turn into a longer discussion, I think it makes sense to discuss this in an extra issue.)

**Comment by z3ntu** [comment]
I was also wondering why the code is hidden behind an #ifdef which doesn't make much sense in my opinion. Yes, the executable could be made a tiny bit smaller by excluding it but as Oliver said, postmarketOS will only have one version packaged.

**Comment by ata2001** [comment]
@ollieparanoid @z3ntu I'm aware, that pmos will only have one version, I was just thinking about other projects, that might want to use it.

But maybe it's just me being a Gentoo user obsessed with USE flags, I can remove them if everyone agrees.

**Comment by pavelmachek** [comment]
Looks good to me. I don't think ifdefs are strictly neccessary, but...

**Comment by ollieparanoid** [comment]
I've compiled and tested it, and it works as expected.

**Pull request merged**
