### PR TITLE
cleaned up a few memory issues

### PR DESCRIPTION
**Pull request by IanS5**
After running it with valgrind I found a few memory issues. I think I fixed most of them here. Valgrind reported more, but it looks like somewhere on the backend there was a leak X11 function that was causing it.

### CODE REVIEW

**Comment by pavelmachek** [comment]
Seems like an improvement from quick review. One day probably whitespace should be cleaned, but...

**Comment by IanS5** [comment]
sorry to sneak that in here, it's kind of along the same lines as the rest of this PR.

**Comment by pavelmachek** [comment]
Are you sure mutex is good idea? Those should only be needed with threads... what is going on there? We should not need threads to do battery monitor.

**Comment by IanS5** [comment]
I just put `update_bat_info` into the main loop and it works fine :P, I have no idea why I originally put it in a separate thread.

**Comment by IanS5** [comment]
@pavelmachek does everything look good here? I know formattings still a problem, ill get that once this PR is merged (see #7)

**Comment by z3ntu** [comment]
You should really fix git to user the correct user/email otherwise github doesn't know that the commits are from you

**Comment by IanS5** [comment]
thanks, although github can figure out who I anyway, it just requests I log in whenever I push

**Comment by pavelmachek** [comment]
Nothing obviously wrong there, so go ahead and merge :-).

**Comment by IanS5** [comment]
:D

**Pull request merged**
